name: Build and Publish Docker

on:
  push:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push SHA
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/enghabu/${{ github.event.repository.name }}:${{ github.event.after }}

      - name: Build and push latest
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'release' }}
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: |
            ghcr.io/enghabu/${{ github.event.repository.name }}:latest
            ghcr.io/enghabu/${{ github.event.repository.name }}:${{ github.event.after }}
